# Generated by Django 5.2.6 on 2025-11-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatar.svg", null=True, upload_to="avatars/"
            ),
        ),
    ]
