# Generated by Django 5.2.6 on 2025-11-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/avatar.svg",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
